import '#modules/user/routes'
import '#modules/auth/routes'
import '#modules/role/routes'
import '#modules/permission/routes'
import '#modules/client/routes'
import '#modules/appointment/routes'
import '#modules/services/routes'
import '#modules/invoice/routes'
